on: [workflow_dispatch]

name: GitHub Actions Ipynb for preflight
jobs:
  preflight:
    runs-on: ubuntu-latest
    name: Ipynb for preflight
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Extract branch name
        shell: bash
        run: echo "GitHub ref_name ${{ github.ref_name }}"
        id: extract_branch
      - name: preflight
        id: preflight
        uses: c2dh/journal-of-digital-history-ipynb-preflight-action@master
        with:
          notebook: 'example/articleMaine.ipynb'
          functions: 'checkkernel,checkcitation,checkhtml,checkoutput,checktags,checkurls,checkjavascript'
          output_md: 'report.md'
      # Use the output from the `preflight` step
      - name: Use the output
        run: echo "Notebook path ${{ steps.preflight.outputs.notebook_path }} - workspace ${{ steps.preflight.outputs.workspace }}"
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: '*.md'
      - name: Run shell cmd
        run: echo "Preflight check on https://github.com/${{github.repository}}/blob/${{github.ref_name}}/${{steps.preflight.outputs.notebook}}"

