on: [workflow_dispatch]

name: GitHub Actions Ipynb
jobs:
  ipynb_for_publishing:
    runs-on: ubuntu-latest
    name: Ipynb for publishing
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: check markdown
        id: preflight
        uses: c2dh/journal-of-digital-history-ipynb-preflight-action@master
        with:
          notebook: 'example/checkmd.ipynb'
          functions: 'checkmd'
      # Use the output from the `preflight` step
      - name: Use the output
        run: echo "number of cells ${{ steps.preflight.outputs.size }} - output ${{ steps.preflight.outputs.checkmd }}"