on: [workflow_dispatch]

name: GitHub Actions Ipynb for preflight
jobs:
  preflight:
    runs-on: ubuntu-latest
    name: Ipynb for preflight
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Extract branch name & create the nbconvert branch
        shell: bash
        run: |
          echo "GitHub ref_name ${{ github.ref_name }}"
          git checkout -b nbconvertt
          git push -u origin nbconvertt
        id: extract_branch
      # - name: preflight
      #   id: preflight
      #   uses: c2dh/journal-of-digital-history-ipynb-preflight-action@nbconvert
      #   with:
      #     notebook: 'example/plotly.ipynb'
      #     functions: 'checkkernel,checkcitation,checkhtml,checkoutput,checktags,checkurls,checkjavascript'
      #     output_md: 'report.md'
      - name: nbconvert run
        run: |
          pip install -r requirements.txt
          python -m pip install jupyter nbconvert nbformat
          python -m spacy download en_core_web_lg
          jupyter nbconvert --execute --to notebook --inplace --ExecutePreprocessor.timeout=-1 checkmd.ipynb
      # Use the output from the `preflight` step
      - name: Use the output
        run: echo "Notebook path ${{ steps.preflight.outputs.notebook_path }} - workspace ${{ steps.preflight.outputs.workspace }}"
      # - name: commit changes
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     file_pattern: '*.md'
      # - name: create pull request
      #   run: gh pr create -B "master" -H "nbconvert" --title 'Merge nbconvert into master' --body 'Created by Github action'
      #   env:
      #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update report
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: nbconvertt
          delete-branch: true
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
          labels: |
            report
            automated pr
          assignees: memerchik
          reviewers: memerchik
          draft: false


      - name: Run shell cmd
        run: echo "Preflight check on https://github.com/${{github.repository}}/blob/${{github.ref_name}}/${{steps.preflight.outputs.notebook}}"

