name: Check Changed Files

on:
  push:
    branches:
      - main

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Retrieve changed files and check for target files
        run: |
          # Retrieve list of changed files between commits
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          echo "Changed files: $CHANGED_FILES"
          
          # Check for the presence of the target files
          HAS_IPYNB=$(echo "$CHANGED_FILES" | grep -w "article.ipynb" || true)
          HAS_MD=$(echo "$CHANGED_FILES" | grep -w "article.md" || true)

          if [[ -n "$HAS_IPYNB" && -n "$HAS_MD" ]]; then
            echo "error"
          elif [[ -n "$HAS_IPYNB" ]]; then
            echo "ipynb"
          elif [[ -n "$HAS_MD" ]]; then
            echo "md"
          else
            echo "No target file changed."
          fi
