name: Check Changed Files on Main

on:
  push:

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check branch and changed files
        run: |
          # Get current branch name by stripping the "refs/heads/" prefix from GITHUB_REF
          BRANCH=${GITHUB_REF#refs/heads/}
          echo "Current branch: $BRANCH"

          # If not on main branch, exit the job early
          if [ "$BRANCH" != "main" ] && [ "$BRANCH" != "master" ]; then
            echo "Not on main branch. Skipping file checks."
            exit 0
          fi

          # Retrieve list of changed files between commits
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          echo "Changed files: $CHANGED_FILES"
          
          # Check for the presence of the target files
          HAS_IPYNB=$(echo "$CHANGED_FILES" | grep -w "article.ipynb" || true)
          HAS_MD=$(echo "$CHANGED_FILES" | grep -w "article.md" || true)

          if [[ -n "$HAS_IPYNB" && -n "$HAS_MD" ]]; then
            echo "error"
          elif [[ -n "$HAS_IPYNB" ]]; then
            echo "ipynb"
          elif [[ -n "$HAS_MD" ]]; then
            echo "md"
          else
            echo "No target file changed."
          fi
