name: Check Changed Files on Main or Master

on:
  push:

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check branch and changed files
        run: |
          # Extract branch name from GITHUB_REF (e.g. "refs/heads/main" becomes "main")
          BRANCH=${GITHUB_REF#refs/heads/}
          echo "Current branch: $BRANCH"
          
          # Proceed only if branch is 'main' or 'master'
          if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "master" ]; then
            echo "main branch"
          else
            echo "Not on main or master branch. Skipping file checks."
            exit 0
          fi
      - name: Get changed files
        run: |
          # Determine how to get changed files:
          # If github.event.before is all zeros, it's likely a new branch or similar situation.
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            echo "No previous commit found. Using last commit for file changes."
            CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD)
          else
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          fi
          echo "Changed files: $CHANGED_FILES"
      - name: Compare the changed files
        run: |
          # Check for the presence of target files
          HAS_IPYNB=$(echo "$CHANGED_FILES" | grep -w "article.ipynb" || true)
          HAS_MD=$(echo "$CHANGED_FILES" | grep -w "article.md" || true)

          if [[ -n "$HAS_IPYNB" && -n "$HAS_MD" ]]; then
            echo "error"
          elif [[ -n "$HAS_IPYNB" ]]; then
            echo "ipynb"
          elif [[ -n "$HAS_MD" ]]; then
            echo "md"
          else
            echo "No target file changed."
          fi
